---
title: "Autodiff"
bibliography: autodiff.bib
---

## How to differentiate

### Basics

- Definition of derivative
- Motivation
- Differentiable programming

### The four horsemen

- Manual
- Symbolic
- Numeric
- Algorithmic
- Computational graph

## The modes of AD

### Forward mode

- Linear maps
- Chain rule
- Link with matrices
- Examples

### Reverse mode

- Adjoint linear maps
- Reverse chain rule
- Link with transposed matrices
- Examples

### Complexity

- Time complexity
- Space complexity
- Checkpointing

### Full matrices

- Choosing a mode
- Solving linear systems

## Implementation

### Principles

- Non-standard interpretation
- Operator overloading
- Source transformation

### Limitations

- Mutation support
- Control flow

### Challenges

- Non-smooth functions
- Approximations
- Solvers as layers

### Solutions

- Writing rules
- Implicit function theorem for continuous optimization layers
- Smoothing for discrete optimization layers

## Software

### Julia libraries

General autodiff: see <https://juliadiff.org/>

- [Enzyme.jl](https://github.com/EnzymeAD/Enzyme.jl)
- [ForwardDiff.jl](https://github.com/JuliaDiff/ForwardDiff.jl)
- [Mooncake.jl](https://github.com/chalk-lab/Mooncake.jl)
- [Zygote.jl](https://github.com/FluxML/Zygote.jl)

Optimization layers:

- [ImplicitDifferentiation.jl](https://github.com/gdalle/ImplicitDifferentiation.jl)
- [DiffOpt.jl](https://github.com/jump-dev/DiffOpt.jl)
- [InferOpt.jl](https://github.com/JuliaDecisionFocusedLearning/InferOpt.jl)

### Python libraries

General autodiff:

- [JAX](https://github.com/jax-ml/jax)
- [PyTorch](https://github.com/pytorch/pytorch)

Optimization layers:

- [Optax](https://github.com/google-deepmind/optax)
- [torchopt](https://github.com/metaopt/torchopt)
- [cvxpylayers](https://github.com/cvxpy/cvxpylayers)
- [PyEPO](https://github.com/khalil-research/PyEPO)

## References

---
nocite: |
  @*
---

::: {#refs}
:::