---
title: "GPU"
bibliography: gpu.bib
---

## Introduction

### Why GPUs?

- Single cores are no longer getting much faster, computing power increases from parallelism
- Initially designed for computer graphics, processing pixels in parallel
- CUDA (2007) made the switch to a general programming interface
- Alexnet (2012) showed they can be used in deep learning
- Most supercomputing capabilities are now GPU-driven, but they are in every laptop too

### CPU versus GPU

- CPU: few cores optimized for sequential, complex operations, low latency, large memory
- GPU: many cores optimized for parallel, simple operations, high throughput, small memory
- GPUs perform many floating point operations per second (100 TFLOPS on Float32, 100x that of CPUs)[^1]
- GPUs have high memory bandwidth (1000 GB/s, 10x that of CPUs)

[^1]: stats given for the NVIDIA L40, similar to the one installed on ENPC's cluster

### Challenges of parallelization

- Additional complexity: performing more work
- Memory-bound applications: number of FLOPs per byte is low
- Heterogeneous, unpredictable input data
- Synchronization operations

## How a GPU works

### Communication

- CPU is the host, GPUs are the devices
- Device code is composed of kernels, executed in a data-parallel manner
- Kernels are interlaced with host instructions, launched asynchronously
- Transfer of data or instructions between CPU and GPU is expensive

### GPU structure

- Grid of blocks (1D, 2D or 3D), each with up to 1024 threads
- Within a block, threads are executed in lockstep (inside warps of 32)
- Single Instruction, Multiple Thread paradigm
- The number of blocks actually executed in parallel is hardware-dependent

### Memory hierarchy

- Host memory + 3 kinds of on-device memory
- Global memory (or DRAM), common across blocks

## GPU kernels

### Contents of a kernel

- Each thread knows its block and thread ID, which replaces a loop
```julia
using KernelAbstractions
@kernel function mul2_kernel(A)
  I = @index(Global)
  A[I] = 2 * A[I]
end
```
- Grid and block shapes are specified by host at kernel launch
```julia
import CUDA
dev = CUDABackend()
A = ones(1024, 1024)
ev = mul2_kernel(dev, 64)(A, ndrange=size(A))
synchronize(dev)
all(A .== 2.0)
```

### Launching kernels

- Kernel launch has overhead
- Kernel fusion at program scale is essential

## Sparse matrices and graphs

### Sparse matrix formats

- COO
- CSR
- SELL
- Hybrid

### SpMV kernels

- COO: atomic operations
- CSR: load balancing issues
- SELL: great but dangerous for high-degree

### Graph algorithms with linear algebra

- GraphBLAS specification
- Custom semirings
- Example: BFS

## Linear and integer programming

### Algorithms for LP

- Simplex: variable-wise updates, linear solve
- Interior point: linear solve
- Primal-dual methods: no linear solve
- Visualization on <https://lpviz.net/>

### What's wrong with linear solves

- Memory overhead of the factorization
- Sparse factorization and updates
- Doesn't scale well on GPU
- Not necessarily the bottleneck

### PDLP

- First-order algorithm with primal and dual variables
- Just matrix-vector multiplications (SpMV)
- Low precision, high scalability
- Original CPU and GPU implementations in Julia (Google, then MIT)

### What makes it go brrrr

- Preconditioning
- Restarting
- Adaptive step size
- Averaging / reflection
- Feasibility polishing

### Areas of improvement

- Presolve
- Crossover
- Hyperparameter tuning

### Algorithms for MILP

- Branch & bound: very sequential
- Cutting planes: very sequential
- Primal heuristics: sometimes parallelizable

### GPU-friendly MILP heuristics

- PDLP as the relaxation solver
- Feasibility pump
- Fix-and-propagate
- Large neighborhood search
- Collaboration between CPU and GPU

## Where to run code?

- On your laptop
  - if your code is hardware-agnostic
  - or if you have a (compatible) GPU
- On the ENPC cluster, see instructions [here](https://github.com/cermics/cluster/blob/main/shared_cluster.md) (private repo)
- On a [Google Colab](https://colab.research.google.com/) notebook

## Julia tooling

### CUDA-specific code

- [CUDA.jl](https://github.com/JuliaGPU/CUDA.jl)
- Math libraries: cuBLAS.jl, cuSPARSE.jl, etc.
- [cuTile.jl](https://github.com/JuliaGPU/cuTile.jl)

### Hardware-agnostic code

- [GPUArrays.jl](https://github.com/JuliaGPU/GPUArrays.jl)
- [KernelAbstractions.jl](https://github.com/JuliaGPU/KernelAbstractions.jl)
- [AcceleratedKernels.jl](https://github.com/JuliaGPU/AcceleratedKernels.jl)
- [Reactant.jl](https://github.com/EnzymeAD/Reactant.jl)

### Deep learning

- [Enzyme.jl](https://github.com/EnzymeAd/Enzyme.jl)
- [Lux.jl](https://github.com/LuxDL/Lux.jl)

### Mathematical programming

Modeling (including batched):

- [JuMP.jl](https://github.com/jump-dev/JuMP.jl)[^1]
- [Convex.jl](https://github.com/jump-dev/Convex.jl)
- [ExaModels.jl](https://github.com/exanauts/ExaModels.jl)
- [BatchNLPKernels.jl](https://github.com/LearningToOptimize/BatchNLPKernels.jl)
- Experimental: [BatchOptInterface.jl](https://github.com/klamike/BatchOptInterface.jl), [BatchQuadraticModels.jl](https://github.com/klamike/BatchQuadraticModels.jl)

[^2]: see the [batching issue](https://github.com/jump-dev/MathOptInterface.jl/issues/2904)

Solvers:

- [Clarabel.jl](https://github.com/oxfordcontrol/Clarabel.jl/tree/CuClarabel)
- [CoolPDLP.jl](https://github.com/JuliaDecisionFocusedLearning/CoolPDLP.jl)
- [cuOpt.jl](https://github.com/jump-dev/cuOpt.jl)
- [cuPDLPx.jl](https://github.com/MIT-Lu-Lab/CuPDLPx.jl)
- [MadIPM.jl](https://github.com/MadNLP/MadIPM.jl)
- [MadNLP.jl](https://github.com/MadNLP/MadNLP.jl)
- [SCS.jl](https://github.com/jump-dev/SCS.jl)

### Graph algorithms

Nothing... yet

## Python tooling

### CUDA-specific code

- [cupy](https://github.com/cupy/cupy)
- [nvmath-python](https://github.com/NVIDIA/nvmath-python)
- [cutile-python](https://github.com/nvidia/cutile-python)

### Hardware-agnostic code

- [Array API](https://github.com/data-apis/array-api/)
- [DLPack](https://github.com/dmlc/dlpack)
- [numba](https://github.com/numba/numba)
- [triton](https://github.com/triton-lang/triton)
- [Pallas](https://docs.jax.dev/en/latest/pallas/index.html)

### Deep learning

- [PyTorch](https://github.com/pytorch/pytorch)
- [JAX](https://github.com/jax-ml/jax)

### Mathematical programming

Modeling:

- [cvxpy](https://github.com/cvxpy/cvxpy/) 
- [pyomo](https://github.com/pyomo/pyomo)

Solvers:

- [cuopt](https://github.com/NVIDIA/cuopt)
- [MPAX](https://github.com/MIT-Lu-Lab/MPAX)

### Graph algorithms

- [networkx](https://github.com/networkx/networkx)
- [cugraph](https://github.com/rapidsai/cugraph)

## References

---
nocite: |
  @*
---

::: {#refs}
:::